# Generated by Django 5.1.1 on 2024-09-27 20:50

import django.contrib.postgres.fields
import tapir.accounts.models
import tapir.core.tapir_email_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20240915_1113"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tapiruser",
            name="additional_mails",
        ),
        migrations.AddField(
            model_name="tapiruser",
            name="optional_mails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=tapir.core.tapir_email_base.get_optional_mails,
                    max_length=128,
                ),
                blank=True,
                default=tapir.accounts.models.get_optional_mails_enabledbydefault,
                size=None,
            ),
        ),
    ]
