# Generated by Django 5.1.1 on 2024-10-20 18:37

import django.db.models.deletion
import tapir.core.tapir_email_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_tapiruser_additional_mails_optionalmails"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=tapir.core.tapir_email_base.get_optional_mails,
                        max_length=256,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="optionalmails",
            name="user-mail-constraint",
        ),
        migrations.RemoveField(
            model_name="optionalmails",
            name="mail_id",
        ),
        migrations.AlterField(
            model_name="optionalmails",
            name="is_requested",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.mail"
            ),
        ),
        migrations.AddConstraint(
            model_name="optionalmails",
            constraint=models.UniqueConstraint(
                fields=("user", "is_requested"), name="user-mail-constraint"
            ),
        ),
    ]
