# Generated by Django 5.1.1 on 2024-10-26 05:36

import tapir.core.tapir_email_base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_mail_remove_optionalmails_user_mail_constraint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="name",
            field=models.CharField(
                choices=tapir.core.tapir_email_base.get_optional_mails,
                max_length=256,
                unique=True,
            ),
        ),
    ]
