# Generated by Django 5.1.1 on 2024-10-26 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_mail_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="optionalmails",
            old_name="is_requested",
            new_name="mail",
        ),
    ]
