# Generated by Django 5.1.1 on 2024-10-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_rename_is_requested_optionalmails_mail"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="optionalmails",
            name="user-mail-constraint",
        ),
        migrations.AddConstraint(
            model_name="optionalmails",
            constraint=models.UniqueConstraint(
                fields=("user", "mail"), name="user-mail-constraint"
            ),
        ),
    ]
